module.exports = {
  awsKeys: {
    AWS_ACCESS_KEY_ID: "HERE COMES THE ACCESS KEY",
    AWS_ACCESS_KEY_SECRET: "HERE COMES THE ACCESS KEY SECRET",
    AWS_BUCKET_NAME: "HERE COMES THE BUCKET NAME",
  },
};
